# Generated by Django 3.2.12 on 2022-02-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(default='user', max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
